<?php

namespace nystudio107\autocomplete\twigextensions;

/**
 * Generated by Craft Autocomplete
 */
class AutocompleteTwigExtension extends \Twig\Extension\AbstractExtension implements \Twig\Extension\GlobalsInterface
{
    public function getGlobals(): array
    {
        return [
            'craft' => new \nystudio107\autocomplete\variables\AutocompleteVariable(),
            'currentSite' => new \craft\models\Site(),
            'currentUser' => new \craft\elements\User(),
            'siteName' => 'English',
            'siteUrl' => 'http://localhost:8080/',
            'systemName' => 'Craft CMS',
            'view' => new \craft\web\View(),
            'devMode' => true,
            'SORT_ASC' => 4,
            'SORT_DESC' => 3,
            'SORT_REGULAR' => 0,
            'SORT_NUMERIC' => 1,
            'SORT_STRING' => 2,
            'SORT_LOCALE_STRING' => 5,
            'SORT_NATURAL' => 6,
            'SORT_FLAG_CASE' => 8,
            'POS_HEAD' => 1,
            'POS_BEGIN' => 2,
            'POS_END' => 3,
            'POS_READY' => 4,
            'POS_LOAD' => 5,
            'isInstalled' => true,
            'loginUrl' => 'http://localhost:8080/login',
            'logoutUrl' => 'http://localhost:8080/logout',
            'setPasswordUrl' => null,
            'now' => new \DateTime(),
            'CraftEdition' => 1,
            'CraftSolo' => 0,
            'CraftPro' => 1,
            'requestedSite' => new \craft\models\Site(),
            'asset' => new \craft\elements\Asset(),
            'category' => new \craft\elements\Category(),
            'entry' => new \craft\elements\Entry(),
            'tag' => new \craft\elements\Tag(),
            'user' => new \craft\elements\User(),
            'nonce' => '',
        ];
    }
}
