field: 4e41f2e1-6f74-4be4-9363-c887bfc9626a # List
fieldLayouts:
  e4636af5-d4a8-4409-9450-e47b3618b456:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c9374344-bf77-4688-a943-48c2840b2a1e # Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07823fdd-af17-44ed-bfc0-e56143357e1c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5bf5bce6-7711-49f4-9bd1-14f0101f3863
        userCondition: null
fields:
  c9374344-bf77-4688-a943-48c2840b2a1e: # Item
    columnSuffix: jekfxqnf
    contentColumnType: text
    fieldGroup: null
    handle: item
    instructions: null
    name: Item
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: newList
name: 'New List'
sortOrder: 1
