columnSuffix: null
contentColumnType: string
fieldGroup: c164b1cf-9cd6-4cea-8349-432bac64860a # Global
handle: infoPanel
instructions: null
name: 'Info Panel'
searchable: false
settings:
  contentTable: '{{%matrixcontent_infopanel}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
