columnSuffix: jgxvpebv
contentColumnType: text
fieldGroup: c164b1cf-9cd6-4cea-8349-432bac64860a # Global
handle: linkTo
instructions: null
name: 'Link To'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
